// sample-bookstore/public/vue/components/Header.vue
<template>
    <header class="header">
        <!-- top navbar -->
        <nav class="navbar navbar-top-bar navbar-static-top">
            <div class="container">
                <ul class="navbar-nav nav">
                    <li><a href="index.html">Home</a></li>
                    <li class="disabled"><a href="index.html">About Us</a></li>
                </ul>
                <ul class="navbar-nav nav navbar-right">
                    <li class="disabled"><a href="#">Login</a></li>
                    <li>
                        <form class="navbar-form" method="get" action="search.html">
                            <div class="form-group">
                                <input name="text" type="text" class="form-control" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default btn-search">Search</button>
                        </form>

                    </li>
                </ul>
            </div>
        </nav>

        <!-- main navigation -->
        <div class="yamm navbar navbar-default navbar-default-book animate-dropdown" role="navigation">
            <div class="container">
                <div class="header-mast">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#KYbook-navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <a class="navbar-brand" href="index.html">
                            <img class="logo" src="../../images/book-flat.png">
                            <span class="title">Quick Start Books</span>
                        </a>
                    </div>
                    <!--
                    <div class="collapse navbar-collapse" id="KYbook-navbar">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a href="index.html">Books</a></li>
                            <li class="disabled"><a href="index.html">Audiobooks</a></li>
                            <li class="disabled"><a href="index.html">Magazines</a></li>
                        </ul>
                    </div>
                    -->
                </div>
            </div>
        </div>

    </header>
</template>

<script>
export default {
    
}
</script>

// angular/angular-toh-app-server/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { Hero } from '../hero';
import { HeroService } from '../hero.service';
import {debounceTime, distinctUntilChanged, switchMap} from "rxjs/operators";
import {Observable, Subject} from "rxjs/index";

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: [ './header.component.css' ]
})
export class HeaderComponent implements OnInit {
  heroes: Hero[] = [];
    heroes$: Observable<Hero[]>;
    private searchTerms = new Subject<string>();

  constructor(private heroService: HeroService) { }

  ngOnInit() {
    this.getHeroes();
  }

  getHeroes(): void {
    this.heroService.getHeroes()
      .subscribe(heroes => this.heroes = heroes);
  }

    search(term: string): void {
      console.log("term",term);
        this.searchTerms.next(term);
    }

    // ngOnInit(): void {
    //     this.heroes$ = this.searchTerms.pipe(
    //
    //         // wait 300ms after each keystroke before considering the term
    //         debounceTime(300),
    //
    //         // ignore new term if same as previous term
    //         distinctUntilChanged(),
    //
    //         // switch to new search observable each time the term changes
    //         switchMap((term: string) => this.heroService.searchHeroes(term)),
    //     );
    // }
}

<header class="header">

    <!-- top navbar -->
    <nav class="navbar navbar-top-bar navbar-static-top">
        <div class="container">
            <ul class="navbar-nav nav">
                <li><a href="index.html">Home</a></li>
                <li class="disabled"><a href="index.html">About Us</a></li>
            </ul>
            <ul class="navbar-nav nav navbar-right">
                <li class="disabled"><a href="#">Login</a></li>
                <li>
                    <form class="navbar-form" method="get" action="search.html">
                        <div class="form-group">
                            <input #searchBox id="search-box" (input)="search(searchBox.value)" type="text" class="form-control" placeholder="Search"/>
                            <!--<input name="text" type="text" class="form-control" placeholder="Search">-->
                        </div>
                        <button type="submit" class="btn btn-default btn-search">Search</button>
                    </form>

                </li>
            </ul>
        </div>
    </nav>

    <!-- main navigation -->
    <div class="yamm navbar navbar-default navbar-default-book animate-dropdown" role="navigation">
        <div class="container">
            <div class="header-mast">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#KYbook-navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="index.html">
                        <img class="logo" src="../images/book-flat.png">
                        <span class="title">Quick Start Books</span>
                    </a>
                </div>
                <!--
                <div class="collapse navbar-collapse" id="KYbook-navbar">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="active"><a href="index.html">Books</a></li>
                        <li class="disabled"><a href="index.html">Audiobooks</a></li>
                        <li class="disabled"><a href="index.html">Magazines</a></li>
                    </ul>
                </div>
                -->
            </div>
        </div>
    </div>

</header>
