// nuxtjs/sample/pages/authors.vue
<template>
     <div class="content">
        <div class="authors page">

          <AuthorList title="Authors" description="Our store features books by several reputable authors:" :authors="authors" />

        </div>
    </div>
</template>

<script>
import AuthorList from "../components/AuthorList";

export default {
    components: {
        AuthorList
    },

    async asyncData({ $branch }) {

        let authors = (await $branch.query({ _type: "store:author" }, { limit: 1000 })).rows;

        return {
            authors: authors
        };
    },

    head() {
        return {
            title: "All Authors"
        }
    }
}
</script>

// sveltekit/sample/src/routes/authors.svelte
<script context="module">
	export const prerender = true;

	export const load = async ({ fetch }) => {
		const res = await fetch('/api/authors?limit=-1', { method: 'POST', body: null}).then(res => res.json());

		return {
			props: {
				authors: res.authors
			}
		}
	};
</script>

<script>
    import AuthorsContainer from '$lib/components/AuthorsContainer.svelte';
	export let authors;

</script>

<svelte:head>
	<title>Authors</title>
</svelte:head>

<section>
    <AuthorsContainer
        authors={authors}
        title="Authors"
        subtitle="Our store features books by several reputable authors:" />
</section>>

<style>
</style>
