// nuxtjs/sample/components/AuthorList.vue
<template>
    <div class="container">
        <div class="wow fadeInUp">
            <div class="module block-featured-author module-block">
                <div class="module-heading">
                    <h2 class="module-title">Featured Authors</h2>
                </div>
                <div class="module-body" id="featured-author">
                    <div class="row">
                        <div class="authors">
                            <div class="col-md-3" v-for="author in authors" v-bind:key="author._doc">
                                <Author v-bind:author="author" />
                            </div>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import axios from 'axios';
import Author from "./Author";

export default {
    components: {
        Author
    },

    data() {
        return {
            authors: []
        };
    },

    created() {
        this.fetchAuthors();
    },

    methods: {
        fetchAuthors() {
            return axios.get('http://localhost:2999/api/authors')
                .then(response => {
                    this.authors = Object.values(response.data);
                    this.authors = this.authors.slice(0, Math.min(4, this.authors.length));
                });
        }
    }
}
</script>

// angular/sample/src/app/Authorlist/authorlist.component.ts
import { Component, OnInit } from '@angular/core';

import { BookService } from '../book.service';

@Component({
    selector: 'app-authorlist',
    templateUrl: './authorlist.component.html'
})
export class AuthorlistComponent implements OnInit {

    authors;

    constructor(private bookService: BookService) { }

    ngOnInit() {
        this.getAuthors();
    }

    getAuthors(): void {
        this.bookService.getAuthors()
            .subscribe(authors => {
                    this.authors = Object.values(authors);
                    this.authors = this.authors.slice(0, Math.min(4, this.authors.length));
                }
            );
    }

}

<div class="container">
    <div class="wow fadeInUp">
        <div class="module block-featured-author module-block">
            <div class="module-heading">
                <h2 class="module-title">Featured Authors</h2>
            </div>
            <div class="module-body" id="featured-author">
                <div class="row">
                    <div class="authors">
                        <div class="col-md-3" *ngFor="let author of authors">
                            <div class="item item-author-block author" style="text-align: center">
                                <a routerLink="/search">
                                    <div class="author-dp">
                                        <img class="img-responsive" alt="" src={{author.imageUrl}} width="258" height="351">
                                    </div>
                                </a>
                                <div class="author-details">
                                    <h3 class="author-name">
                                        <a routerLink="/search">
                                            {{author.title}}
                                        </a>
                                    </h3>
                                    <!--<blockquote class="author-testimonial">{{author.testimonial}}</blockquote>-->
                                    <a routerLink="/search" class="btn btn-primary btn-view-books">
                                        View books
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
