// bookstore/react-site/src/components/AuthorsContainer.js
import React from 'react'
import Author from './Author'
import { Container, Row, Col } from 'react-bootstrap';

class AuthorsContainer extends React.Component {

  render() {
    const firstFourAuthors = this.props.authors.slice(0, 4);

    return (
      <div className="featured-item-block">
        <Container>
            <div className="module block-featured-author module-block">
              <div className="module-heading">
                <h2 className="module-title">Featured Authors</h2>
              </div>
              <div className="module-body" id="featured-author">
                <div className="authors">
                  <Row>
                    {
                      firstFourAuthors.map((author) => (
                        <Col sm="3" key={author._doc}>
                          <Author author={author} />
                        </Col>
                      ))
                    }
                  </Row>
                </div>
              </div>
            </div>
        </Container>
      </div>
    )
  }
}

export default AuthorsContainer

// sveltekit/sample/src/lib/components/AuthorsContainer.svelte
<script>
    import Author from './Author.svelte';
    export let authors;
    export let title;
    export let subtitle;

    const firstFourAuthors = authors.slice(0, 4);
</script>

<div class="featured-item-block">
    <div class="container">
        <div class="wow fadeInUp">
            <div class="module block-featured-author module-block">
                <div class="module-heading">
                    <h2 class="module-title">{title}</h2>
                    <p class="module-subtitle">{subtitle}</p>
                </div>
                <div class="module-body" id="featured-author">
                    <div class="authors">
                        <div class="row">
                            {#each firstFourAuthors as author}
                                <div class="col-md-3" key={author._doc}>
                                    <Author author={author} />
                                </div>
                            {/each}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
</style>
