// sample-bookstore/public/react/components/BookTags.js
import React, { Fragment } from "react";

const styleH4 = {
    display: "inline-block"
}

const styleA = {
    color: "white"
}

const BookTags = ({ book }) => (
    <Fragment>
        <h3>Tags</h3>
        <div>
            {
                book.tags.map((tag) => (
                    <h4 style={styleH4} key={tag}>
                        <span className="label label-default"><a href={`tags.html?id=${tag}`} style={styleA}>{tag}</a></span>
                    </h4>
                ))
            }
        </div>
    </Fragment>
)

export default BookTags

// sveltekit/sample/src/lib/components/BookTags.svelte
<script>
    export let book;
</script>

<template>
    <h3>Tags</h3>
    <div>
        {#each book.tags as tag}
            <h4 key={tag}>
                <span class="label label-default">
                    <p>{tag}</p>
                </span>
            </h4>
        {/each}
    </div>
</template>

<style>
    h4 {
        display: inline-block;
    }

    p {
        color: white;
    }
</style>
