// bookstore/react-site/src/components/BooksContainer.js
import React from 'react'
import { Container, Row, Col } from 'react-bootstrap';
import Book from './Book'

class BooksContainer extends React.Component {

  constructor(props) {
    super(props);

    props.books.forEach((book) => {
      if (!book._doc)
      {
        book._doc = book.id;
      }
    });
  }

  render() {
    const firstFourBooks = this.props.books.slice(0, 4);

    return (
      <Container>
        <div className="module block-new-books module-block">
          <div className="module-heading">
            <h2 className="module-title">{this.props.title}</h2>
            <p className="module-subtitle">{this.props.subtitle}</p>
          </div>
          <div className="module-body">
            <div className="books">
              <Row>
                {
                  firstFourBooks.map((book) => (
                    <Col sm="3" key={book._doc}>
                      <Book book={book} />
                    </Col>
                  ))
                }
              </Row>
            </div>
          </div>
        </div>
      </Container>
    )
  }
}

export default BooksContainer

// sveltekit/sample/src/lib/components/BooksContainer.svelte
<script>
    import Book from './Book.svelte';

    export let books;
    export let title;
    export let subtitle;

    const firstFourBooks = books.slice(0, 4);
</script>

<div class="container">
    <div class="wow fadeInUp">
        <div class="module block-new-books module-block">
            <div class="module-heading">
                <h2 class="module-title">{title}</h2>
                <p class="module-subtitle">{subtitle}</p>
            </div>
            <div class="module-body">
                <div class="books">
                    <div class="row">
                        {#each firstFourBooks as book}
                            <div class="col-md-3" key={book._doc}>
                                <Book book={book} />
                            </div>
                        {/each}
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<style>
</style>
