// sample-bookstore/public/react/components/Navmain.js
import React from "react";

const Navmain = () => (
    <div className="yamm navbar navbar-default navbar-default-book animate-dropdown" role="navigation">
        <div className="container">
            <div className="header-mast">

                <div className="navbar-header">
                    <button type="button" className="navbar-toggle" data-toggle="collapse" data-target="#KYbook-navbar">
                        <span className="sr-only">Toggle navigation</span>
                        <span className="icon-bar"></span>
                        <span className="icon-bar"></span>
                        <span className="icon-bar"></span>
                    </button>
                    <a className="navbar-brand" href="index.html">
                        <img className="logo" src="../images/book-flat.png" />
                        <span className="title">Quick Start Books</span>
                    </a>
                </div>
            </div>
        </div>
    </div>
)

export default Navmain

// sveltekit/sample/src/lib/components/Navmain.svelte
<script>
	import { page } from '$app/stores';
</script>

<div class="yamm navbar navbar-default navbar-default-book animate-dropdown" role="navigation">
    <div class="container">
        <div class="header-mast">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#KYbook-navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                    <img class="logo" src={"/images/book-flat.png"} alt="logo" />
                    <span class="title">Quick Start Books</span>
                </a>
            </div>
        </div>
    </div>
</div>

<style>
</style>
