// sample-bookstore/public/react/components/Slider.js
import React from "react";

const Slider = (props) => (
    <div className="slider">
        <div id="hero">
            <div id="owl-main" className="owl-carousel1 owl-theme">
                <div className="item">
                <div className="container">
                    <div className="content caption">
                        <div className="row">
                            <div className="col-sm-5 col-sm-push-7">
                                <div className="book-in-shelf">
                                    <div className="book-shelf">
                                        <div className="book-cover slider-book-cover">
                                            <img className="img-responsive" alt="" src={props.bookItem.imageUrl} width="258" height="351" />
                                            <div className="fade"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="col-sm-7 col-sm-pull-5">
                                <div className="clearfix slider-caption">
                                    <div className="slider-caption-heading">
                                        <h1 className="slider-caption-title fadeInDown-1">{props.bookItem.title}</h1>
                                        <p className="slider-caption-subtitle fadeInDown-2 hidden-xs">{props.bookItem.description}</p>
                                    </div>
                                    <div className="clearfix slider-price fadeInDown-3 hidden-xs">
                                        <a className="btn btn-secondary btn-price" href="#">${props.bookItem.price}</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
)

export default Slider

// sveltekit/sample/src/lib/components/Slider.svelte
<script>
    export let book;
</script>

<div class="slider">
    <div id="hero">
        <div id="owl-main" class="owl-carousel1 owl-theme">
            <div class="item">
                <div class="container">
                    <div class="content caption">
                        <div class="row">
                            <div class="col-sm-5 col-sm-push-7">
                                <div class="book-in-shelf">
                                    <div class="book-shelf">
                                        <div class="book-cover slider-book-cover">
                                            <img class="img-responsive" alt="" src={book.defaultAttachmentUrl} width="258" height="351" />
                                            <div class="fade"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-7 col-sm-pull-5">
                                <div class="clearfix slider-caption">
                                    <div class="slider-caption-heading">
                                        <h1 class="slider-caption-title fadeInDown-1">{book.title}</h1>
                                        <p class="slider-caption-subtitle fadeInDown-2 hidden-xs">{book.description}</p>
                                    </div>
                                    <div class="clearfix slider-price fadeInDown-3 hidden-xs">
                                        <a href={`/book/${book.slug}`}>
                                            <span class="btn btn-secondary btn-price">View Book</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .slider {
        height: 600;
        background-color: "#629c49";
    }
</style>
