// sveltekit/sample/src/routes/books.svelte
<script context="module">
	export const prerender = true;

	export const load = async ({ fetch }) => {
		const res = await fetch('/api/books?limit=-1', { method: 'POST'}).then(res => res.json());

		return {
			props: {
				books: res.books
			}
		}
	};
</script>

<script>
    import BooksContainer from '$lib/components/BooksContainer.svelte';
	export let books;

</script>

<svelte:head>
	<title>Books</title>
</svelte:head>

<section>
    <BooksContainer
        books={books}
        title="Books"
        subtitle="Choose from our fine selection of books" />
</section>>

<style>
</style>

// nuxtjs/sample/pages/books.vue
<template>
     <div class="content">
        <div class="books page">

          <BookList title="Books" description="Choose from our fine selection of books" :books="books" />

        </div>
    </div>
</template>

<script>
import BookList from "../components/BookList";

export default {
    components: {
        BookList
    },

    async asyncData({ $branch }) {

        let books = (await $branch.queryNodes({ _type: "store:book" }, { limit: 1000 })).rows;

        return {
            books: books
        };
    },

    head() {
        return {
            title: "All Books"
        }
    }
}
</script>
