// sample-bookstore/public/react/components/Author.js
import React from "react";
import { Link } from "react-router-dom";

const Author = ({ author }) => (
    <div className="item item-author-block author">
        <Link to={`/author/${author._doc}`}>
            <div className="author-dp">
                <img src={author.imageUrl} alt={author.title} />
            </div>
        </Link>
        <div className="author-details">
            <h3 className="author-name">
                <Link to={`author/${author._doc}`}>
                    {author.title}
                </Link>
            </h3>
            <Link to={`/search`} className="btn btn-primary btn-view-books">
                View Books
            </Link>
        </div>
    </div>
)

export default Author

// sample-bookstore/public/vue/components/Author.vue
<template>
    <div class="item item-author-block author">
        <router-link to="/search">
            <div class="author-dp">
                <img v-bind:src="author.imageUrl"  v-bind:alt="author.title">
            </div>
        </router-link>        
        <div class="author-details">
            <h3 class="author-name">
                <router-link tag="a" to="/search">{{author.title}}</router-link>
            </h3>
            <blockquote class="author-testimonial">{{author.testimonial}}</blockquote>
            <router-link tag="a" to="/search" class="btn btn-primary btn-view-books">View books</router-link>
        </div>
    </div>
</template>

<script>
export default {
    props: {
        author: {
            type: Object,
            required: true
        }
    }
}
</script>
