// angular-bookstore/src/app/BookCarousel/bookcarousel.component.ts
import { Component, OnInit } from '@angular/core';

import { Bookcarousel } from '../bookcarousel';
import { BookcarouselService } from '../bookcarousel.service';

@Component({
  selector: 'app-bookcarousel',
  templateUrl: './bookcarousel.component.html'
})
export class BookCarouselComponent implements OnInit {

    books;

  constructor(private bookCarouselService: BookcarouselService) { }

  ngOnInit() {
    this.getHeroes();
  }

  getHeroes(): void {
    this.bookCarouselService.getHeroes()
        .subscribe(books => {
                this.books = Object.values(books);
            }
        );
  }


}

<div class="wow fadeInUp">
    <div class="module block-new-books module-block">
        <div class="module-heading">
            <h2 class="module-title">New Books</h2>
            <div class="customNavigation">
            </div>
            <p class="module-subtitle">Do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
        </div>

        <div class="module-body">
            <div class="books">
                <!--<div id="new-carousel" class="owl-carousel home-owl-carousel">-->
                <div class="item item-carousel" *ngFor="let book of books">
                    <div>
                        {{book._doc}}
                    <a routerLink="/book/{{book._doc}}">
                        {{book.name}}
                    </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// sample-bookstore/public/vue/components/BookCarousel.vue
<template>
    <div class="wow fadeInUp">
        <div class="module block-new-books module-block">
            <div class="module-heading">
                <h2 class="module-title">New Books</h2>
                <div class="customNavigation">
                    <div data-target="#new-carousel" class="btn btn-navigation left-nav-arrow owl-prev"><i class='icon fa fa-caret-left'></i></div>
                    <div data-target="#new-carousel" class="btn btn-navigation right-nav-arrow owl-next"><i class='icon fa fa-caret-right'></i></div>
                </div>
                <p class="module-subtitle">Do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
            </div>

            <div class="module-body">
                <div class="books">
                    <div id="new-carousel" class="owl-carousel home-owl-carousel">
                        <div class="item item-carousel" v-for="book in books" :key="book._doc">
                            <Book v-bind:book="book" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import axios from 'axios';

import Book from "./Book";

export default {
    components: {
        Book
    },

    data() {
        return {
            books: []
        }
    },

    created() {
        this.fetchBooks();
    },

    methods: {
        fetchBooks() {
            return axios.get('/api/books')
                .then(response => {
                    this.books = Object.values(response.data);
                });
        }
    }
};
</script>
