// angular/sample/src/app/Bookcarousel/bookcarousel.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { BookService } from '../book.service';

@Component({
    selector: 'app-bookcarousel',
    templateUrl: './bookcarousel.component.html'
})
export class BookcarouselComponent implements OnInit {

    @Input()
    books;

    constructor(private bookService: BookService) { }

    ngOnInit() {
        if (!this.books)
        {
            this.getBooks();
        }
    }

    getBooks(): void {
        this.bookService.getBooks()
            .subscribe(books => {
                    this.books = Object.values(books);
                    this.books = this.books.slice(0, Math.min(4, this.books.length));
                }
            );
    }

}

<div class="container">
    <div class="wow fadeInUp">
        <div class="module block-new-books module-block">
            <div class="module-heading">
                <h2 class="module-title">New Books</h2>
                <p class="module-subtitle">Do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
            </div>

            <div class="module-body">
                <div class="books">
                    <div class="row">
                        <div class="col-md-3" *ngFor="let book of books">
                            <app-book [book]="book" [width]="255" [height]="261"></app-book>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

// sample-bookstore/public/vue/components/BookCarousel.vue
<template>
    <div class="wow fadeInUp">
        <div class="module block-new-books module-block">
            <div class="module-heading">
                <h2 class="module-title">New Books</h2>
                <div class="customNavigation">
                    <div data-target="#new-carousel" class="btn btn-navigation left-nav-arrow owl-prev"><i class='icon fa fa-caret-left'></i></div>
                    <div data-target="#new-carousel" class="btn btn-navigation right-nav-arrow owl-next"><i class='icon fa fa-caret-right'></i></div>
                </div>
                <p class="module-subtitle">Do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
            </div>

            <div class="module-body">
                <div class="books">
                    <div id="new-carousel" class="owl-carousel home-owl-carousel">
                        <div class="item item-carousel" v-for="book in books" :key="book._doc">
                            <Book v-bind:book="book" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import axios from 'axios';

import Book from "./Book";

export default {
    components: {
        Book
    },

    data() {
        return {
            books: []
        }
    },

    created() {
        this.fetchBooks();
    },

    methods: {
        fetchBooks() {
            return axios.get('/api/books')
                .then(response => {
                    this.books = Object.values(response.data);
                });
        }
    }
};
</script>
