// angular-bookstore/src/app/header/header.component.ts
import { Component, OnInit } from '@angular/core';

import { Observable, Subject } from 'rxjs';

import {
   debounceTime, distinctUntilChanged, switchMap
 } from 'rxjs/operators';

import { Hero } from '../hero';
import { HeroService } from '../hero.service';

@Component({
  selector: 'app-hero-search',
  templateUrl: './header.component.html'
})
export class HeroSearchComponent implements OnInit {
  heroes$: Observable<Hero[]>;
  private searchTerms = new Subject<string>();

  constructor(private heroService: HeroService) {}

  // Push a search term into the observable stream.
  search(term: string): void {
    this.searchTerms.next(term);
  }

  ngOnInit(): void {
    this.heroes$ = this.searchTerms.pipe(
      // wait 300ms after each keystroke before considering the term
      debounceTime(300),

      // ignore new term if same as previous term
      distinctUntilChanged(),

      // switch to new search observable each time the term changes
      switchMap((term: string) => this.heroService.searchHeroes(term)),
    );
  }
}

<header class="header">
    <!-- top navbar -->
    <nav class="navbar navbar-top-bar navbar-static-top">
        <div class="container">
            <ul class="navbar-nav nav">
                <router-link tag="li" to="/"><a>Home</a></router-link>
                <li class="disabled"><a href="index.html">About Us</a></li>
            </ul>
            <ul class="navbar-nav nav navbar-right">
                <li class="disabled"><a href="#">Login</a></li>
                <li>
                    <div class="navbar-form">
                        <div class="form-group">
                            <input #searchBox id="search-box" (input)="search(searchBox.value)" type="text" class="form-control" placeholder="Search"/>
                            <!-- <input v-model="searchQuery" v-on:keyup.enter="search" type="text" class="form-control" placeholder="Search"> -->
                        </div>
                        <!-- <a class="btn btn-default btn-search" v-on:click.stop="search">Search</a> -->
                    </div>

                </li>
            </ul>
        </div>
    </nav>

    <!-- main navigation -->
    <div class="yamm navbar navbar-default navbar-default-book animate-dropdown" role="navigation">
        <div class="container">
            <div class="header-mast">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#KYbook-navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <router-link tag="a" class="navbar-brand" to="/">
                        <img class="logo" src="../images/book-flat.png">
                        <span class="title">Quick Start Books</span>
                    </router-link>
                </div>
            </div>
        </div>
    </div>

</header>

// sample-bookstore/public/vue/components/Header.vue
<template>
    <header class="header">
        <!-- top navbar -->
        <nav class="navbar navbar-top-bar navbar-static-top">
            <div class="container">
                <ul class="navbar-nav nav">
                    <router-link tag="li" to="/"><a>Home</a></router-link>
                    <li class="disabled"><a href="index.html">About Us</a></li>
                </ul>
                <ul class="navbar-nav nav navbar-right">
                    <li class="disabled"><a href="#">Login</a></li>
                    <li>
                        <div class="navbar-form">
                            <div class="form-group">
                                <input v-model="searchQuery" v-on:keyup.enter="search" type="text" class="form-control" placeholder="Search">
                            </div>
                            <a class="btn btn-default btn-search" v-on:click.stop="search">Search</a>
                        </div>

                    </li>
                </ul>
            </div>
        </nav>

        <!-- main navigation -->
        <div class="yamm navbar navbar-default navbar-default-book animate-dropdown" role="navigation">
            <div class="container">
                <div class="header-mast">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#KYbook-navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <router-link tag="a" class="navbar-brand" to="/">
                            <img class="logo" src="../../images/book-flat.png">
                            <span class="title">Quick Start Books</span>
                        </router-link>
                    </div>
                    <!--
                    <div class="collapse navbar-collapse" id="KYbook-navbar">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a href="index.html">Books</a></li>
                            <li class="disabled"><a href="index.html">Audiobooks</a></li>
                            <li class="disabled"><a href="index.html">Magazines</a></li>
                        </ul>
                    </div>
                    -->
                </div>
            </div>
        </div>

    </header>
</template>

<script>
export default {
    data() {
        return {
            searchQuery: ""
        }
    },

    methods: {
        search() {
            this.$router.push({
                path: "/search",
                query   : {
                    text: this.searchQuery
                }
            });
        }
    }
}
</script>
