// angular/sample/src/app/Header/header.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

import {
    debounceTime, distinctUntilChanged, switchMap
} from 'rxjs/operators';


@Component({
  selector: 'app-header',
  templateUrl: './header.component.html'
})
export class HeaderComponent {

     constructor(private router: Router) { }

    search(term: string): void {
        this.router.navigate(['/search'], {
            queryParams: {
                text: term
            }
        });
    }
}

<header class="header">

    <!-- top navbar -->
    <nav class="navbar navbar-top-bar navbar-static-top">
        <div class="container">
            <ul class="navbar-nav nav">
                <li><a href="index.html">Home</a></li>
                <li class="disabled"><a href="index.html">About Us</a></li>
            </ul>
            <ul class="navbar-nav nav navbar-right">
                <li class="disabled"><a href="#">Login</a></li>
                <li>
                    <form class="navbar-form" method="get" action="search.html">
                        <div class="form-group">
                            <input #searchBox id="search-box" (keyup.enter)="search(searchBox.value)" type="text" class="form-control" placeholder="Search"/>

                        </div>

                        <a class="btn btn-default btn-search" [routerLink]="['./search']" (click)="search(searchBox.value)">Search</a>
                    </form>

                </li>
            </ul>
        </div>
    </nav>

    <!-- main navigation -->
    <div class="yamm navbar navbar-default navbar-default-book animate-dropdown" role="navigation">
        <div class="container">
            <div class="header-mast">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#KYbook-navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="index.html">
                        <img class="logo" src="images/book-flat.png">
                        <span class="title">Quick Start Books</span>
                    </a>
                </div>
            </div>
        </div>
    </div>

</header>

// sample-bookstore/public/vue/components/Header.vue
<template>
    <header class="header">
        <!-- top navbar -->
        <nav class="navbar navbar-top-bar navbar-static-top">
            <div class="container">
                <ul class="navbar-nav nav">
                    <li><a href="index.html">Home</a></li>
                    <li class="disabled"><a href="index.html">About Us</a></li>
                </ul>
                <ul class="navbar-nav nav navbar-right">
                    <li class="disabled"><a href="#">Login</a></li>
                    <li>
                        <form class="navbar-form" method="get" action="search.html">
                            <div class="form-group">
                                <input name="text" type="text" class="form-control" placeholder="Search">
                            </div>
                            <button type="submit" class="btn btn-default btn-search">Search</button>
                        </form>

                    </li>
                </ul>
            </div>
        </nav>

        <!-- main navigation -->
        <div class="yamm navbar navbar-default navbar-default-book animate-dropdown" role="navigation">
            <div class="container">
                <div class="header-mast">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#KYbook-navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>

                        <a class="navbar-brand" href="index.html">
                            <img class="logo" src="../../images/book-flat.png">
                            <span class="title">Quick Start Books</span>
                        </a>
                    </div>
                    <!--
                    <div class="collapse navbar-collapse" id="KYbook-navbar">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a href="index.html">Books</a></li>
                            <li class="disabled"><a href="index.html">Audiobooks</a></li>
                            <li class="disabled"><a href="index.html">Magazines</a></li>
                        </ul>
                    </div>
                    -->
                </div>
            </div>
        </div>

    </header>
</template>

<script>
export default {
    
}
</script>
