// sample-bookstore/public/vue/components/Book.vue
<template>
    <div class="books">
        <div class="book">
            <div class="book-cover">
                <div class="book-inner">
                    <a v-bind:href="bookLink">
                        <img v-bind:src="book.imageUrl" v-bind:alt="book.title">
                    </a>
                    <div class="fade"></div>
                    <div class="book-price">
                        <span class="price">
                            $ {{book.price}}
                        </span>
                    </div>
                </div>
            </div>
            <div class="book-details">
                <router-link tag="h3" class="book-title" v-bind:to="bookLink"><a>{{book.title}}</a></router-link>
                <p class="book-author">{{book.authorTitle}}</p>
                <div class="star-rating">
                    <!-- <i class="fa fa-star {{#lte 1 book.rating}}color{{/lte}}"></i>
                    <i class="fa fa-star {{#lte 2 book.rating}}color{{/lte}}"></i>
                    <i class="fa fa-star {{#lte 3 book.rating}}color{{/lte}}"></i>
                    <i class="fa fa-star {{#lte 4 book.rating}}color{{/lte}}"></i>
                    <i class="fa fa-star {{#lte 5 book.rating}}color{{/lte}}"></i> -->
                </div>
            </div>
        </div>
    </div>
</template>

<script>
export default {
    props: {
        book: {
            type: Object,
            required: true
        }
    },

    data() {
        return {
            bookLink: "/book/" + this.book._doc
        };
    }
};
</script>

// bookstore/react-site/src/components/Book.js
import React, { Component } from 'react';
import { Row, Col, Container, Carousel } from 'react-bootstrap';
import { Link } from 'react-router-dom';


class FeaturedBook extends Component {
  constructor(props) {
    super(props);
    if (props.book.author)
    {
      props.book.authorTitle = props.book.author.title;
    }
    else
    {
      props.book.authorTitlte = "None";
    }

    if (!props.book._doc)
    {
      props.book._doc = props.book.id;
    }
  }

  render() {
    return (
      <div className="book">
        <div className="book-cover">
          <div className="book-inner">
          <Link to={`/book/${this.props.book._doc}`}>
            <img className="list-book padded" src={this.props.book.imageUrl} alt={this.props.book.title} />
          </Link>
          </div>
        </div>
        <div className="book-details">
            <h3 className="book-title">
              <Link to={`/book/${this.props.book._doc}`}>
                {this.props.book.title}
              </Link>
            </h3>
            <p className="book-author">{this.props.book.authorTitle}</p>
        </div>
      </div>
    );
  }
}
export default FeaturedBook;
