// angular/sample/src/app/Bookitem/bookitem.component.ts
import { Component, Input } from "@angular/core";

import { Book } from '../book';

@Component({
    selector: 'app-book',
    templateUrl: './bookitem.component.html'
})
export class BookItemComponent  {
    @Input() width: string;
    @Input() height: string;
    @Input() book: Book;

};
<div class="book" style="text-align: center">
    <div class="book-cover">
        <div class="book-inner">
            <img alt="" src={{book.imageUrl}} width="255" height="261">
            <div class="fade"></div>
        </div>
    </div>
    <div class="book-details">
        <h3 class="book-title">
            <a routerLink="/book/{{book._doc}}">{{book.title}}</a>
        </h3>
        <p class="book-author">{{book.authorTitle}}</p>
    </div>
</div>

// sample-bookstore/public/react/components/BookItem.js
import React from "react";

const BookItem = (props) => (
    <div className="item item-carousel">
    <div className="books">
        <div className="book">
            <div className="book-cover">
                <div className="book-inner">
                    <a href={`book.html?id=${props.bookItem._doc}`}>
                        <img src={props.bookItem.imageUrl} alt={props.bookItem.title} />
                    </a>
                    <div className="fade"></div>
                </div>
            </div>
            <div className="book-details">
                <h3 className="book-title">
                    <a href={`book.html?id=${props.bookItem._doc}`}>
                        {props.bookItem.title}
                    </a>
                </h3>
                <p className="book-author">{props.bookItem.authorTitle}</p>
            </div>
        </div>
    </div>
</div>
)

export default BookItem
