// sample-bookstore/public/vue/components/Book.vue
<template>
    <div class="book">
            <div v-if="sale" class="sale-ribbon"><div class="sale-ribbon-content">sale off</div></div>
        <div class="book-cover">
            <div class="book-inner">
                <a v-bind:href="bookLink">
                    <img v-bind:src="book.imageUrl" v-bind:alt="book.title" v-bind:width="width" v-bind:height="height">
                </a>
                <div class="fade"></div>
            </div>
        </div>
        <div class="book-details">
            <router-link tag="h3" class="book-title" v-bind:to="bookLink"><a>{{book.title}}</a></router-link>
            <p class="book-author">{{book.authorTitle}}</p>
        </div>
    </div>
</template>

<script>
export default {
    props: {
        book: {
            type: Object,
            required: true
        },
        width: {
            type: String,
        },
        height: {
            type: String,
        },
        sale: {
            type: Boolean,
            default: false
        }
    },

    data() {
        return {
            bookLink: "/book/" + this.book._doc
        };
    }
};
</script>

// sample-bookstore/public/react/components/Book.js
import React from "react";
import { Link } from "react-router-dom";

class SaleRibbon extends React.Component {
    render () {
        if (window.location.href.indexOf("search") < 0) {
            return null;
        }

        return (
            <div className="sale-ribbon"><div className="sale-ribbon-content">sale off</div></div>
        )
    }
}

const Book = ({ book }) => (
    <div className="book">
        <SaleRibbon />
        <div className="book-cover">
            <div className="book-inner">
                <Link to={`/book/${book._doc}`}>
                    <img src={book.imageUrl} alt={book.title} />
                </Link>
                <div className="fade"></div>
            </div>
        </div>
        <div className="book-details">
            <h3 className="book-title">
                <Link to={`/book/${book._doc}`}>
                    {book.title}
                </Link>
            </h3>
            <p className="book-author">{book.authorTitle}</p>
        </div>
    </div>
)

export default Book
