// sveltekit/sample/src/lib/components/Navbar.svelte
<script>
	import { page } from '$app/stores';
</script>

<nav class="navbar navbar-top-bar navbar-static-top">
    <div class="container">
        <ul class="navbar-nav nav">
            <li>
                <a href="/">Home</a>
            </li>
            <li>
                <a href="/books">Books</a>
            </li>
            <li>
                <a href="/authors">Authors</a>
            </li>
            <li>
                <a href="/tags">Tags</a>
            </li>
        </ul>
    </div>
</nav>

<style>
</style>

// sample-bookstore/public/react/components/Navbar.js
import React from "react";
import { Link } from "react-router-dom";
import NavForm from "./NavForm";

const Navbar = () => (
  <nav className="navbar navbar-top-bar navbar-static-top">
    <div className="container">
      <ul className="navbar-nav nav">
        <li><Link to="/">Home</Link></li>
        <li className="disabled"><Link to="/">About Us</Link></li>
      </ul>
    </div>
    <ul className="navbar-nav nav navbar-right">
      <li className="disabled"><a href="#">Login</a></li>
      <li>
        <NavForm />
      </li>
    </ul>
  </nav>
)

export default Navbar
